Issue 5
LorenzoBettini/attsw-exercise pull request #22
Opened 2017-11-28 15:11 UTC by FrancescoTerrosi

Closes #5

2017-11-28 15:27 UTC, Wabri approved these changes

2017-11-29 07:40 UTC, LorenzoBettini requested changes

2017-11-29 07:40 UTC, LorenzoBettini commented on exercise-parent/pom.xml
> +    <jacoco.report.path>${project.reporting.outputDirectory}/jacoco-ut</jacoco.report.path>
This property is useless, and it's never used

2017-11-29 07:40 UTC, LorenzoBettini commented on exercise-parent/pom.xml
> +                  <!-- binds by *default* to the phase "verify" -->
why the * ?

2017-11-29 13:07 UTC, FrancescoTerrosi commented
My bad for the useless property and the *default*, should be ok now

2017-11-29 13:17 UTC, Wabri approved these changes

2017-11-29 16:59 UTC, LorenzoBettini approved these changes

2017-11-29 17:00 UTC, merged